export const usersData = [
  {
    id: 1,
    name: 'ironman',
    img: require('../assets/ironman.jpg'),
    country: require('../assets/africa.jpg'),
    category: 'Astrologer',
  },
  {
    id: 2,
    name: 'hulk',
    img: require('../assets/Hulk.jpg'),
    country: require('../assets/ind.png'),
    category: 'Assistant',
  },
  {
    id: 3,
    name: 'spiderman',
    img: require('../assets/spiderman.jpg'),
    country: require('../assets/Aus.jpg'),
    category: 'Mehendi',
  },
  {
    id: 4,
    name: 'thanos',
    img: require('../assets/thanos.webp'),
    country: require('../assets/Arg.jpg'),
    category: 'Makeup',
  },
  {
    id: 5,
    name: 'wolverine',
    img: require('../assets/wolverine.jpg'),
    country: require('../assets/italy.jpg'),
    category: 'Photo',
  },
  {
    id: 6,
    name: 'Thor',
    img: require('../assets/thor.webp'),
    country: require('../assets/spain.png'),
    category: 'Photo',
  },
  {
    id: 7,
    name: 'stan',
    img: require('../assets/stan.png'),
    country: require('../assets/ind.png'),
    category: 'Makeup',
  },
  {
    id: 8,
    name: 'venom',
    img: require('../assets/venom.jpg'),
    country: require('../assets/Aus.jpg'),
    category: 'Mehendi',
  },
  {
    id: 9,
    name: 'marvel',
    img: require('../assets/marvel.jpg'),
    country: require('../assets/ind.png'),
    category: 'Assistant',
  },
  {
    id: 10,
    name: 'rdj',
    img: require('../assets/rdj.jpg'),
    country: require('../assets/spain.png'),
    category: 'Astrologer',
  },
  {
    id: 11,
    name: 'Ultron',
    img: require('../assets/ultron.webp'),
    country: require('../assets/italy.jpg'),
    category: 'Astrologer',
  },
  {
    id: 12,
    name: 'dr',
    img: require('../assets/dr.jpg'),
    country: require('../assets/africa.jpg'),
    category: 'Makeup',
  },
  {
    id: 13,
    name: 'scarlet',
    img: require('../assets/scarlet.jpg'),
    country: require('../assets/Arg.jpg'),
    category: 'Mehendi',
  },
  {
    id: 14,
    name: 'sam',
    img: require('../assets/sam.jpg'),
    country: require('../assets/Aus.jpg'),
    category: 'Assistant',
  },
  {
    id: 15,
    name: 'Debra',
    img: require('../assets/photo.png'),
    country: require('../assets/ind.png'),
    category: 'Photo',
  },
  {
    id: 16,
    name: 'Channel',
    img: require('../assets/Astrologer.jpg'),
    country: require('../assets/spain.png'),
    category: 'Astrologer',
  },
];

export const categories = [
  {img: require('../assets/Astrologer.jpg'), name: 'Astrologer'},
  {img: require('../assets/assistant.png'), name: 'Assistant'},
  {img: require('../assets/mehendi.jpg'), name: 'Mehendi'},
  {img: require('../assets/makeup.png'), name: 'Makeup'},
  {img: require('../assets/photo.png'), name: 'Photo'},
];
